### PR TITLE
Update to 1.20.1

### PR DESCRIPTION
**Pull request by mnfu**
- bump minecraft version
- bump yarn mappings version
- bump fabric loader version
- bump mod version
- bump fabric api version

- update loom 0.12 ->1.2
- update gradle 7.3 -> 8.1.1
- fix small issue with building related to 1.20 command feedback change

### CODE REVIEW

**Comment by mnfu** [comment]
Also was unsure of how you do your versioning, it seems like you changed it last when you committed in February, if that needs changed lmk

**Comment by mnfu** [comment]
Mod has been updated 👍

**Comment by spoorn** [comment]
sorry, I didn't see this PR.  If you'd like, you could update the PR with some of the changes as I see you updated other dependencies and I can merge it.  Up to you

**Comment by mnfu** [comment]
All good haha, no need. Thanks for updating it!

**Pull request closed without merging**
